---
title: "STAT 545B Assignment B4 Exercise 1"
output: github_document
---

Reference: https://dk81.github.io/dkmathstats_site/rtext-freq-words.html
Stopwords from: tidytext::stop_words

```{r}
library(dplyr)
library(tidytext)
library(ggplot2)
library(janeaustenr)
```

```{r}
# Data frame: Pride and Prejudice from Jane Austen
pride_prejudice <- tibble(Text = janeaustenr::prideprejudice)
head(pride_prejudice)
```

```{r}
# Picks individual words and places them as rows
pride_prejudice_words <- pride_prejudice %>% 
                  unnest_tokens(output = word, input = Text) 
head(pride_prejudice_words)
```

```{r}
# Remove stopwords using anti_join()
# Then convert into a work count tibble
pride_prejudice_words <- pride_prejudice_words %>%
                   anti_join(stop_words) %>% 
                   count(word, sort = TRUE)
head(pride_prejudice_words)
```

```{r}
# Plot the most common words
pride_prejudice_words %>% 
  filter(n > 150) %>% # Pick word with more than 150 counts
  mutate(word = reorder(word, n)) %>% 
    ggplot(aes(word, n)) + 
    geom_col() +
    coord_flip() +
    labs(x = "Word", y = "Count", title = "Common Words in Pride and Prejudice") +
    geom_text(aes(label = n), colour = "white", hjust = 1.2) +
    theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face="bold"),
        axis.title.y = element_text(face="bold"))
```

